In [4]:
#libraries
from googleapiclient.discovery import build
import pandas as pd
import seaborn as sns

## Function to get channel statistics

In [5]:
# get api from google cloud api
api_key = 'AIzaSyAK0koduEe3JM5R6UoFT0YOHv_wTR_mFac'

#channel id of Channel what you want to extract
channel_ids = ['UClZF7OsrECe3t_ADrjZEh_Q', #get mp3 
              'UCYr-8h4I30iFBp_R3Ej1Wtw',#get mp3 punjabi
              'UCpx43GnPYdqFXWnsuxLaljQ', # getmp3 haryanvi
               'UCW6cVdRxRuhk8nhg1pd3PNg' #getmp3 devotional
             ]
#youtube service
youtube = build('youtube','v3',developerKey=api_key)

In [6]:
# channel statistics data
def get_channel_stats(youtube,channel_ids):
    all_data = []
    request = youtube.channels().list(
        part = 'snippet,contentDetails,statistics',
        id=','.join(channel_ids)
    )
    response = request.execute()

    for i in range(len(response['items'])):
        data = dict(channel_name = response['items'][i]['snippet']['title'],
                   subscripbers = response['items'][i]['statistics']['subscriberCount'],
                   views=response['items'][i]['statistics']['viewCount'],
                   total_videos = response['items'][i]['statistics']['videoCount'],
                   playlist_id = response['items'][i]['contentDetails']['relatedPlaylists']['uploads'])
        all_data.append(data)
    return all_data

In [7]:
channel_statistics = get_channel_stats(youtube,channel_ids)

In [8]:
channel_data = pd.DataFrame(channel_statistics)

In [9]:
channel_data

,channel_name,subscripbers,views,total_videos,playlist_id
0,Geet MP3 Punjabi,254000,184298718,228,UUYr-8h4I30iFBp_R3Ej1Wtw
1,Geet MP3 Haryanvi,258000,125197788,80,UUpx43GnPYdqFXWnsuxLaljQ
2,Geet MP3,36900000,16309892289,849,UUlZF7OsrECe3t_ADrjZEh_Q
3,Geet MP3 Devotional,35300,4331778,21,UUW6cVdRxRuhk8nhg1pd3PNg

## Function to get video ids

In [10]:
channel_data

,channel_name,subscripbers,views,total_videos,playlist_id
0,Geet MP3 Punjabi,254000,184298718,228,UUYr-8h4I30iFBp_R3Ej1Wtw
1,Geet MP3 Haryanvi,258000,125197788,80,UUpx43GnPYdqFXWnsuxLaljQ
2,Geet MP3,36900000,16309892289,849,UUlZF7OsrECe3t_ADrjZEh_Q
3,Geet MP3 Devotional,35300,4331778,21,UUW6cVdRxRuhk8nhg1pd3PNg

# Geet MP3 Punjabi

In [11]:
playlist_id_get_punjabi = channel_data.loc[channel_data['channel_name']=='Geet MP3 Punjabi','playlist_id'].iloc[0]
playlist_id_get_punjabi

'UUYr-8h4I30iFBp_R3Ej1Wtw'

In [12]:
# video playlist statistics
def get_video_ids(youtube,playlist_id):

    request = youtube.playlistItems().list(
        part='contentDetails,snippet',
        playlistId = playlist_id,
        maxResults = 50)
    response = request.execute()
    video_info = []

    for i in range(len(response['items'])):

        info = dict(
                channel_title = response['items'][i]['snippet']['channelTitle'],
                song_name = response['items'][i]['snippet']['title'],
                release_date = response['items'][i]['snippet']['publishedAt'],
                description = response['items'][i]['snippet']['description'],
                video_id = response['items'][i]['contentDetails']['videoId']    
        )
        video_info.append(info)

    next_page_token = response.get('nextPageToken')
    more_page = True

    while more_page:
        if next_page_token is None:
            more_page = False
        else:
            request = youtube.playlistItems().list(
                        part='contentDetails,snippet',
                        playlistId = playlist_id,
                        maxResults = 50,
                pageToken = next_page_token)
            response = request.execute()

            for i in range(len(response['items'])):
                
                info = dict(
                        channel_title = response['items'][i]['snippet']['channelTitle'],
                        song_name = response['items'][i]['snippet']['title'],
                        release_date = response['items'][i]['snippet']['publishedAt'],
                        description = response['items'][i]['snippet']['description'],
                        video_id = response['items'][i]['contentDetails']['videoId']    
                )
                video_info.append(info)
            next_page_token = response.get('nextPageToken')
   
    return video_info

In [13]:
get_video_ids(youtube,playlist_id_get_punjabi)

[{'channel_title': 'Geet MP3 Punjabi',
  'song_name': 'Splendor (8K Full Video) : Satbir Aujla | Sharry Nexus | Latest Punjabi Songs - Geet MP3',
  'release_date': '2026-10-15T12:30:05Z',
  'description': 'Geet MP3 presents the enhanced 8K full video of “Splendor,” beautifully sung, written, and composed by Satbir Aujla, with music produced by Sharry Nexus. Enjoy the song now in stunning 8K visuals with enhanced clarity and an improved viewing experience.\n\nStream/ Download "Splendor" on:\n\nSpotify: https://open.spotify.com/track/5i4OV4brkR3tdDiMHQYfLj\nApple Music: https://music.apple.com/us/album/splendor-single/1760236402\niTunes: https://music.apple.com/us/album/splendor-single/1760236402\nAmazon Music India: https://music.amazon.in/albums/B0DBMV6TDG\nGaana: https://gaana.com/song/splendor-18\nJio Saavn: https://www.jiosaavn.com/album/splendor/ngijjITR-Xc_\nYT Music: https://music.youtube.com/watch?v=5vFy5NwBJ4g&si=LAh8f2OmiLJwxUe9&drli=1\nInstagram Reel: https://www.instagram.com/reels/audio/367953054298813\n\nSong Credits:\n\nTitle: Splendor\nSinger: Satbir Aujla\nLyrics: Satbir Aujla\nComposer: Satbir Aujla\nMusic: Sharry Nexus\nVideo: Rav Dhillon\nProduced by: KV Dhillon\nLabel: Geet MP3 Punjabi\n\nSubscribe Geet MP3 Punjabi for Unlimited Entertainment: https://bit.ly/3ASEhWh\n\nGet In Touch With Us on Social Media:\n\nWebsite: https://www.geetmp3.com/\nInstagram: https://www.instagram.com/geetmp3punjabii/\nFacebook: https://www.facebook.com/GeetMP3Punjabi\nLinkedin: https://www.linkedin.com/company/geet-mp3\nTwitter: htthttps://twitter.com/GeetMP3Universe\nSnapchat: https://www.snapchat.com/add/GeetMP3\nYoutube Channel: https://www.youtube.com/@GeetMP3PunjabiOfficial',
  'video_id': 'RqKaqJCAg2M'},
 {'channel_title': 'Geet MP3 Punjabi',
  'song_name': 'Jimmy Choo Choo (8K Full Video) : Guri | B Praak | Jaani | Latest Punjabi Songs - Geet MP3',
  'release_date': '2026-10-13T12:30:03Z',
  'description': 'Geet MP3 presents the enhanced 8K video of “Saiyaan,” beautifully sung by Guri, featuring rap vocals by Ikka, music produced by B Praak, and lyrics penned by Jaani. Now enjoy the song in stunning 8K visuals.\n\nStream/ Download "Jimmy Choo Choo" on:\n\nSpotify: https://open.spotify.com/track/0oVevFsf5j4GKpof0CiQ8X\nApple Music: https://music.apple.com/us/album/jimmy-choo-choo-single/1760238034\niTunes: https://music.apple.com/us/album/jimmy-choo-choo-single/1760238034\nAmazon Prime Music: https://music.amazon.in/tracks/B0DBMZXHRJ\nGaana: https://gaana.com/song/jimmy-choo-choo-1\nJio Saavn: https://www.jiosaavn.com/album/jimmy-choo-choo/UwTjOZ4o,jg_\nYT Music: https://music.youtube.com/playlist?list=OLAK5uy_mwgGrd4Qgt55RdM3F-NobGocFyKp5uWLM&si=NU-tMr7ncMrzzkn8\nInstagram Reel: https://www.instagram.com/reels/audio/1914072232218724\n\nSong Credits:\n\nSong: Jimmy Choo Choo\nSinger: Guri\nRap: Ikka\nMusic: B Praak\nLyrics: Jaani\nVideo: Arvindr Khaira\nProduced by: KV Dhillon\nLabel: Geet MP3 Punjabi\n\nSubscribe Geet MP3 Punjabi for Unlimited Entertainment: https://bit.ly/3ASEhWh\n\nGet In Touch With Us on Social Media:\n\nWebsite: https://www.geetmp3.com/\nInstagram: https://www.instagram.com/geetmp3punjabii/\nFacebook: https://www.facebook.com/GeetMP3Punjabi\nLinkedin: https://www.linkedin.com/company/geet-mp3\nTwitter: htthttps://twitter.com/GeetMP3Universe\nSnapchat: https://www.snapchat.com/add/GeetMP3\nYoutube Channel: https://www.youtube.com/@GeetMP3PunjabiOfficial',
  'video_id': 'v59drV-bHH4'},
 {'channel_title': 'Geet MP3 Punjabi',
  'song_name': 'Rabb Wangu (8K Full Video) : Jass Manak | Latest Punjabi Songs - Geet MP3',
  'release_date': '2026-10-10T12:30:40Z',
  'description': 'Geet MP3 presents the enhanced 8K video of “Rabb Wnagu,” beautifully sung, penned, and composed by Jass Manak, with music produced by Sharry Nexus. Now enjoy the song in stunning 8K visuals.\n\nStream/ Download "Rabb Wangu" on:\n\nSpotify: https://spoti.fi/3RDCsiy\nApple Music: https://apple.co/3CYgvGR\niTunes: https://apple.co/3CYgvGR\nJio Saavn: https://bit.ly/3Qnpkx0\nYT Music: https://bit.ly/3cL81rZ\nInstagram Reel: https://bit.ly/3QjO3Ct\n\nSong Credits :\n\nSong: Rabb Wangu\nSinger: Jass Manak\nLyrics: Jass Manak\nComposer: Jass Manak\nMusic: Sharry Nexus\nProduced By: KV Dhillon\nMusic Label: Geet MP3\n\nSubscribe Geet MP3 Punjabi for Unlimited Entertainment: https://bit.ly/3ASEhWh\n\nGet In Touch With Us on Social Media:\n\nWebsite: https://www.geetmp3.com/\nInstagram: https://www.instagram.com/geetmp3punjabii/\nFacebook: https://www.facebook.com/GeetMP3Punjabi\nLinkedin: https://www.linkedin.com/company/geet-mp3\nTwitter: htthttps://twitter.com/GeetMP3Universe\nSnapchat: https://www.snapchat.com/add/GeetMP3\nYoutube Channel: https://www.youtube.com/@GeetMP3PunjabiOfficial',
  'video_id': '4khclgs-m8o'},
 {'channel_title': 'Geet MP3 Punjabi',
  'song_name': 'Juti Jharrke (8K Full Video) : Hardeep Grewal | Afsana Khan | Latest Punjabi Songs - Geet MP3',
  'release_date': '2026-10-05T12:30:14Z',
  'description': 'Geet MP3 presents the enhanced 8K video of “Juti Jharrke,” a duet beautifully sung by Hardeep Grewal & Afsana Khan, with music produced by Proof. Now enjoy the song in stunning 8K visuals.\n\nStream/ Download "Juti Jharrke" on:\n\nSpotify: https://open.spotify.com/album/43BECgyBHPVq4Gb89MBfAF\nApple Music: https://music.apple.com/us/album/juti-jharrke-single/1760235820\niTunes: https://music.apple.com/us/album/juti-jharrke-single/1760235820\nAmazon Music India: https://music.amazon.in/albums/B0DBN1TN51\nGaana: https://gaana.com/song/juti-jharrke-1\nJio Saavn: https://www.jiosaavn.com/album/juti-jharrke/qllVjljgBNA_\nYT Music: https://music.youtube.com/playlist?list=OLAK5uy_kxZ1Mk6y0eItbl8pI9cBVSSHy5weAljAo&si=neesVByysmGSp9vg\nInstagram Reel: https://www.instagram.com/reels/audio/467100340586626\n\nSong Credits:\n\nSong: Juti Jharrke\nSinger: Hardeep Grewal\nLyrics: Hardeep Grewal\nComposer: Hardeep Grewal\nFemale Singer: Afsana Khan\nMusic: Proof\nVideo By: Garry Khatrao Media\nProduced by: KV Dhillon\nLabel: Geet MP3 Punjabi\n\nSubscribe Geet MP3 Punjabi for Unlimited Entertainment: https://bit.ly/3ASEhWh\n\nGet In Touch With Us on Social Media:\n\nWebsite: https://www.geetmp3.com/\nInstagram: https://www.instagram.com/geetmp3punjabii/\nFacebook: https://www.facebook.com/GeetMP3Punjabi\nLinkedin: https://www.linkedin.com/company/geet-mp3\nTwitter: htthttps://twitter.com/GeetMP3Universe\nSnapchat: https://www.snapchat.com/add/GeetMP3\nYoutube Channel: https://www.youtube.com/@GeetMP3PunjabiOfficial',
  'video_id': 'jOKAP9Hx0vY'},
 {'channel_title': 'Geet MP3 Punjabi',
  'song_name': 'Saiyaan (8K Full Video) : Jass Manak | Sanjeeda Shaikh | Latest Punjabi Songs - Geet MP3',
  'release_date': '2026-10-02T12:29:31Z',
  'description': 'Geet MP3 presents the enhanced 8K video of “Saiyaan,” beautifully sung, penned, and composed by Jass Manak, with music produced by Sharry Nexus. Now enjoy the song in stunning 8K visuals.\n\nStream/ Download "Saiyaan" on:\n\nSpotify: https://open.spotify.com/album/2bUKXxtDHMle5hi1mDISRz\nApple Music: https://music.apple.com/us/album/saiyaan-single/1760237393\niTunes: https://music.apple.com/us/album/saiyaan-single/1760237393\nAmazon Music India: https://music.amazon.in/albums/B0DBMX2ZXX\nGaana: https://gaana.com/song/saiyaan-63\nJio Saavn: https://www.jiosaavn.com/album/saiyaan/o4TwkIWc63U_\nYT Music: https://music.youtube.com/watch?v=mPJKdS-fBSU&si=0Ub14X6AgNYcLi8D\nInstagram Reel: https://www.instagram.com/reels/audio/479525794825881\n\nSong: Saiyaan \nSinger: Jass Manak\nLyrics: Jass Manak\nComposer: Jass Manak \nMusic: Sharry Nexus\nFeaturing: Sanjeeda Shaikh\nVideo: Satti Dhillon\nProduced by: KV Dhillon\nLabel: Geet MP3 Punjabi\n\nSubscribe Geet MP3 Punjabi for Unlimited Entertainment: https://bit.ly/3ASEhWh\n\nGet In Touch With Us on Social Media:\n\nWebsite: https://www.geetmp3.com/\nInstagram: https://www.instagram.com/geetmp3punjabii/\nFacebook: https://www.facebook.com/GeetMP3Punjabi\nLinkedin: https://www.linkedin.com/company/geet-mp3\nTwitter: htthttps://twitter.com/GeetMP3Universe\nSnapchat: https://www.snapchat.com/add/GeetMP3\nYoutube Channel: https://www.youtube.com/@GeetMP3PunjabiOfficial',
  'video_id': 'nfYa2ZQfVBY'},
 {'channel_title': 'Geet MP3 Punjabi',
  'song_name': 'Jass Manak (All Songs) | Jass Manak All Punjabi Songs - Latest Punjabi Songs - Geet MP3',
  'release_date': '2026-09-24T09:35:27Z',
  'description': 'Geet MP3 Presents the Full Jukebox Audio of Jass Manak, featuring some of his most loved and nostalgic hits. \n\nSit back, relax, and enjoy a collection of songs that bring back memories, emotions, and timeless Punjabi vibes. From soulful melodies to feel-good tracks, this jukebox is perfect for a long drive, late-night listening, or simply enjoying your favourite Jass Manak songs.\n\nSubscribe Geet MP3 Punjabi for Unlimited Entertainment: https://bit.ly/3ASEhWh\n\nGet In Touch With Us on Social Media:\n\nWebsite: https://www.geetmp3.com/\nInstagram: https://www.instagram.com/geetmp3punjabii/\nFacebook: https://www.facebook.com/GeetMP3Punjabi\nLinkedin: https://www.linkedin.com/company/geet-mp3\nTwitter: htthttps://twitter.com/GeetMP3Universe\nSnapchat: https://www.snapchat.com/add/GeetMP3\nYoutube Channel: https://www.youtube.com/@GeetMP3PunjabiOfficial',
  'video_id': 'TnW9BYo-sZ8'},
 {'channel_title': 'Geet MP3 Punjabi',
  'song_name': 'Heeriye (8k Full Video) : Arjun Sahota | Gagan Dhillon | Satti Dhillon | Latest Punjabi Songs 2026',
  'release_date': '2026-09-02T12:30:01Z',
  'description': 'Geet MP3 presents 8k Full Video of romantic song "Heeriye" by Arjun Sahota. The song is beautifully written by Arjun Sahota with soulful music produced by Gagan Dhillon. This song captures love, emotions, and heartfelt vibes in the most melodious way.\n\nStream/Download "Heeriye" on :\n\nSpotify: https://open.spotify.com/album/787SyrOt227kOP2pzyIdaF\nApple Music: https://music.apple.com/us/album/heeriye-single/6798987080\niTunes: https://music.apple.com/us/album/heeriye-single/6798987080\nJioSaavn: https://www.jiosaavn.com/album/heeriye/rRnRtFXSSBU_\nGaana: https://gaana.com/song/heeriye-VWR7gZmObd\nAmazon Prime Music: https://music.amazon.in/albums/B0HDBYGHYC\nYouTube Music: https://music.youtube.com/playlist?list=OLAK5uy_lLnCavdZ2rh0UggSZk0G13aQ84l4tifKs&si=46yLdF41YmhYkrJQ\nInstagram Reel: https://www.instagram.com/reels/audio/1595667885248355\n\nSong Credits: \n\nTitle: Heeriye\nSinger: Arjun Sahota\nLyrics: Arjun Sahota\nComposer: Arjun Sahota\nMusic Composer: Gagan Dhillon\nVideo: Satti Dhillon\nDOP: Vikcee\nIndiana Production Goa\nLine Producer: Naezen D’Souza\nProduction Manager: Ravin Gopal\nDrone & BTS: Amit Raj\nEdit: Mr Editor \nColour: Onkar\nCamera & Lights: D&A Production \nHair & Makeup: Swati Saini\nDressmen: Masood Shaikh\nSpot: Fareed Alam & Sarfraz Ali\nOnline Promotions: OVA Digital\nProducer: KV Dhillon\nRecord Label: Geet MP3\n\nJoin the Journey and Subscribe to Endless Entertainment: http://bit.ly/SubscribeGEETMP3\n\nEnjoy & Stay Connected With us On Social Media:\n\nLinkedin: https://www.linkedin.com/company/geet-mp3\nYouTube: https://www.youtube.com/c/GeetMP3 \nFacebook: https://www.facebook.com/iGeetMP3\nInstagram: https://www.instagram.com/GeetMP3\nTwitter: htthttps://twitter.com/GeetMP3Universe\nSnapchat: https://www.snapchat.com/add/GeetMP3\nWebsite: http://GeetMP3.com',
  'video_id': 'lNs10mghW3s'},
 {'channel_title': 'Geet MP3 Punjabi',
  'song_name': 'Guitar (8K Full Video) : Karan Randhawa | Ayesha Khan | Latest Punjabi Songs - Geet MP3',
  'release_date': '2026-08-31T12:30:04Z',
  'description': 'Geet MP3 presents the 8K video of \'Guitar\' sung by Karan Randhawa with featuring of Ayesha Khan, lyrics penned by Fateh Shergill while soothing music is produced by V Barot, now  enjoy the same vibe with enhanced visuals.\n\nStream/ Download "Guitar" on:\n\nSpotify: https://open.spotify.com/track/5IG7VuYedEhg3t7AacfirW\nApple Music: https://music.apple.com/us/album/guitar-single/1760237929\niTunes: https://music.apple.com/us/album/guitar-single/1760237929\nAmazon Prime Music: https://music.amazon.in/albums/B0DBNFGKK1\nGaana: https://gaana.com/song/guitar-214\nJio Saavn: https://www.jiosaavn.com/album/guitar/oFprvlK,tyg_\nYT Music: https://music.youtube.com/watch?v=xaUZhsDzRJ4&si=G0_KJ13Htd5jqGfR\nInstagram Reel: https://www.instagram.com/reels/audio/588981409395472\n\nSong Credits:\n\nTitle: Guitar\nSinger: Karan Randhawa (Ft. Ayesha Khan)\nLyrics: Fateh Shergill\nMusic: V Barot\nVideo: Rav Dhillon\nProduced by: KV Dhillon\nLabel: Geet MP3 Punjabi\n\nSubscribe Geet MP3 Punjabi for Unlimited Entertainment: https://bit.ly/3ASEhWh\n\nGet In Touch With Us on Social Media:\n\nWebsite: https://www.geetmp3.com/\nInstagram: https://www.instagram.com/geetmp3punjabii/\nFacebook: https://www.facebook.com/GeetMP3Punjabi\nLinkedin: https://www.linkedin.com/company/geet-mp3\nTwitter: htthttps://twitter.com/GeetMP3Universe\nSnapchat: https://www.snapchat.com/add/GeetMP3\nYoutube Channel: https://www.youtube.com/@GeetMP3PunjabiOfficial',
  'video_id': 'Ltl-o0f73TY'},
 {'channel_title': 'Geet MP3 Punjabi',
  'song_name': 'Istanbul (Full Song) Bhanu Pratap Agnihotri | Sahil | Latest Punjabi Songs 2026 - Geet MP3',
  'release_date': '2026-08-18T12:30:02Z',
  'description': 'Geet MP3 presents the full Punjabi romantic song “Istanbul”, sung by Bhanu Pratap Agnihotri and penned by Sahil. A soulful romantic track filled with love, emotions, and beautiful vibes—perfect for every romantic playlist.\n\nStream/ Download "Istanbul" on:\n\nSpotify: https://open.spotify.com/album/17LszvF2utGdeZ554bVC9d\nApple Music: https://music.apple.com/us/album/istanbul-single/6798345152\niTunes: https://music.apple.com/us/album/istanbul-single/6798345152\nAmazon Prime Music: https://music.amazon.in/albums/B0HD1DTKMM\nGaana: https://gaana.com/song/istanbul-4WEpBlGd3P\nJio Saavn: https://www.jiosaavn.com/album/istanbul/9DfU4I,n80c_\nYT Music: https://music.youtube.com/watch?v=CY_m9zUycVY&si=o5A-qXoJlXYIbbrY\nInstagram Reel: https://www.instagram.com/reels/audio/2256885638381508\n\nSong Credits:\n\nTitle: Istanbul\nSinger: Bhanu Pratap Agnihotri\nLyrics: Sahil\nMusic: Bhanu Pratap Agnihotri\nComposer: Bhanu Pratap Agnihotri\nOnline Promotions: OVA Digital\nProduced by: KV Dhillon\nLabel: Geet MP3 Punjabi\n\nSubscribe Geet MP3 Punjabi for Unlimited Entertainment: https://bit.ly/3ASEhWh\n\nGet In Touch With Us on Social Media:\n\nWebsite: https://www.geetmp3.com/\nInstagram: https://www.instagram.com/geetmp3punjabii/\nFacebook: https://www.facebook.com/GeetMP3Punjabi\nLinkedin: https://www.linkedin.com/company/geet-mp3\nTwitter: htthttps://twitter.com/GeetMP3Universe\nSnapchat: https://www.snapchat.com/add/GeetMP3\nYoutube Channel: https://www.youtube.com/@GeetMP3PunjabiOfficial',
  'video_id': '0OHUVp8SbH4'},
 {'channel_title': 'Geet MP3 Punjabi',
  'song_name': 'ROMANTIC AMLI : VADDA GREWAL (Official Video) Raka | Latest Punjabi Songs 2026 - Geet MP3',
  'release_date': '2026-08-05T12:30:01Z',
  'description': 'Geet MP3 presents the full video of “Romantic Amli” sung by Vadda Grewal, with lyrics penned by Vadda Grewal and Raka, and music composed by Meavin, a perfect punjabi song to vibe on.\n\nStream/ Download "Romantic Amli" on:\n\nSpotify: https://open.spotify.com/album/7C0S0vjfKmfTj1Rye3Z1xY\nApple Music: https://music.apple.com/us/album/romantic-amli-single/6797013185\niTunes: https://music.apple.com/us/album/romantic-amli-single/6797013185\nAmazon Prime Music: https://music.amazon.in/albums/B0HCJW1M8M\nGaana: https://gaana.com/song/romantic-amli\nJio Saavn: https://www.jiosaavn.com/album/romantic-amli/FcgsZX-anyE_\nYT Music: https://music.youtube.com/watch?v=EQTEB6iugcA&si=iDIX0GfIt7cpYoe4\nInstagram Reel: https://www.instagram.com/reels/audio/1515390913601960\n\nSong Credits: \n\nTitle: Romantic Amli\nSinger: Vadda Grewal\nLyrics: Vadda Grewal, Raka\nMusic: Meavin\nMusic Composer: Vadda Grewal, Meavin\nVideo: Jagroop Sandhu, Guru Bhullar\nDOP: Jass Sudan\nFemale Lead: Param Grewal\nProduced by: KV Dhillon\nLabel: Geet MP3 Punjabi\n\nSubscribe Geet MP3 Punjabi for Unlimited Entertainment: https://bit.ly/3ASEhWh\n\nGet In Touch With Us on Social Media:\n\nWebsite: https://www.geetmp3.com/\nInstagram: https://www.instagram.com/geetmp3punjabii/\nFacebook: https://www.facebook.com/GeetMP3Punjabi\nLinkedin: https://www.linkedin.com/company/geet-mp3\nTwitter: htthttps://twitter.com/GeetMP3Universe\nSnapchat: https://www.snapchat.com/add/GeetMP3\nYoutube Channel: https://www.youtube.com/@GeetMP3PunjabiOfficial',
  'video_id': 'F1KK4-hWjrU'},
 {'channel_title': 'Geet MP3 Punjabi',
  'song_name': 'Boss (8K Full Video) : Jass Manak | Satti Dhillon | Latest Punjabi Songs - Geet MP3',
  'release_date': '2026-07-31T12:30:29Z',
  'description': 'Geet MP3 presents the 8K full video of "Boss" by Jass Manak. The music is produced by Game Changerz, and the video is directed by Satti Dhillon, now enjoy with 8K enahnced visuals.\n\nStream/ Download "Boss" on:\n\nSpotify: https://open.spotify.com/album/2MMQ94NytBAZCwT6XPWUnG\nApple Music: https://music.apple.com/us/album/boss-single/1760235338\niTunes: https://music.apple.com/us/album/boss-single/1760235338\nAmazon Prime Music: https://music.amazon.in/albums/B0DBMW35KK\nGaana: https://gaana.com/album/boss-punjabi-2019\nJio Saavn: https://www.jiosaavn.com/album/boss/MdmEHCtok5I_\nYT Music: https://music.youtube.com/watch?v=XqB1nzANoQM&si=aBEOxV1xXCw09w_S\nInstagram Reel: https://www.instagram.com/reels/audio/1039191744818459\n\nSong Credits:\n\nTitle: Boss\nSinger: Jass Manak\nLyrics: Jass Manak\nComposer: Jass Manak\nMusic: Game Changerz\nVideo: Satti Dhillon\nProduced by: KV Dhillon\nLabel: Geet MP3 Punjabi\n\nSubscribe Geet MP3 Punjabi for Unlimited Entertainment: https://bit.ly/3ASEhWh\n\nGet In Touch With Us on Social Media:\n\nWebsite: https://www.geetmp3.com/\nInstagram: https://www.instagram.com/geetmp3punjabii/\nFacebook: https://www.facebook.com/GeetMP3Punjabi\nLinkedin: https://www.linkedin.com/company/geet-mp3\nTwitter: htthttps://twitter.com/GeetMP3Universe\nSnapchat: https://www.snapchat.com/add/GeetMP3\nYoutube Channel: https://www.youtube.com/@GeetMP3PunjabiOfficial',
  'video_id': 'q_hCoCOtr9o'},
 {'channel_title': 'Geet MP3 Punjabi',
  'song_name': 'Lambo Car (8K Full Video) : Guri | Simar Kaur | Neha Sharma | Latest Punjabi Songs 2026 - Geet MP3',
  'release_date': '2026-07-27T12:30:17Z',
  'description': 'Geet MP3 presents the 8k full video of "Lambo Car" by Guri with female vocals of Simar Kaur and the music produced by Sukhe.\n\nDownload/ Stream "Lambo Car" on\n\nSpotify : https://spoti.fi/2KAlLr6\nGaana : https://bit.ly/3q0S5Ul\nApple Music : https://apple.co/2V47wNh\nPrime Music : https://amzn.to/3oeYJF1\nJio Saavn : https://bit.ly/39iLyOY\nHungama : https://bit.ly/2IUzRmV\nWynk : https://bit.ly/3nXJMa3\nYT Music : https://bit.ly/364EEea\niTunes : https://apple.co/2V47wNh\nResso : https://bit.ly/3nZDbfa\n\nSong Credits:\n\nSong : Lambo Car\nStarring : Guri x Neha Sharma\nSinger : Guri\nLyrics : Guri\nComposer : Guri\nMusic : Sukhe \nFemale Vocals : Simar Kaur \nStory & Direction : Satti Dhillon \nProduced by: KV Dhillon\nLabel: Geet MP3 Punjabi\n\nSubscribe Geet MP3 Punjabi for Unlimited Entertainment: https://bit.ly/3ASEhWh\n\nGet In Touch With Us on Social Media:\n\nWebsite: https://www.geetmp3.com/\nInstagram: https://www.instagram.com/geetmp3punjabii/\nFacebook: https://www.facebook.com/GeetMP3Punjabi\nLinkedin: https://www.linkedin.com/company/geet-mp3\nTwitter: htthttps://twitter.com/GeetMP3Universe\nSnapchat: https://www.snapchat.com/add/GeetMP3\nYoutube Channel: https://www.youtube.com/@GeetMP3PunjabiOfficial',
  'video_id': 'Z3bSG5Gq6Zo'},
 {'channel_title': 'Geet MP3 Punjabi',
  'song_name': 'BAD MUNDA (8K Full Video) : Jass Manak Ft. Emiway Bantai | Deep Jandu | Latest Punjabi Songs',
  'release_date': '2026-07-21T12:29:56Z',

In [14]:
video_ids_punjabi = get_video_ids(youtube,playlist_id_get_punjabi)

In [15]:
len(video_ids_punjabi)

228

In [16]:
punjabi_song_df = pd.DataFrame(video_ids_punjabi)
punjabi_song_df.head()

,channel_title,song_name,release_date,description,video_id
0,Geet MP3 Punjabi,Splendor (8K Full Video) : Satbir Aujla | Shar...,2026-10-15T12:30:05Z,Geet MP3 presents the enhanced 8K full video o...,RqKaqJCAg2M
1,Geet MP3 Punjabi,Jimmy Choo Choo (8K Full Video) : Guri | B Pra...,2026-10-13T12:30:03Z,Geet MP3 presents the enhanced 8K video of “Sa...,v59drV-bHH4
2,Geet MP3 Punjabi,Rabb Wangu (8K Full Video) : Jass Manak | Late...,2026-10-10T12:30:40Z,Geet MP3 presents the enhanced 8K video of “Ra...,4khclgs-m8o
3,Geet MP3 Punjabi,Juti Jharrke (8K Full Video) : Hardeep Grewal ...,2026-10-05T12:30:14Z,Geet MP3 presents the enhanced 8K video of “Ju...,jOKAP9Hx0vY
4,Geet MP3 Punjabi,Saiyaan (8K Full Video) : Jass Manak | Sanjeed...,2026-10-02T12:29:31Z,Geet MP3 presents the enhanced 8K video of “Sa...,nfYa2ZQfVBY

In [17]:
all_video_ids = punjabi_song_df['video_id']
all_video_ids[0]

'RqKaqJCAg2M'

In [18]:
len(all_video_ids)

228

## Function to get video details

In [19]:
# video data staticstics - title,lang,duration,likes,views,comments
def get_video_details(youtube,video_ids):
    all_video_stats = []
    
    for i in range(0,len(video_ids),50):
        request = youtube.videos().list(
                part ='snippet,statistics,contentDetails',
                id = ','.join(video_ids[i:i+50]))
              
        response = request.execute()

        if 'items' in response:
            for video in response['items']:
                video_stats = dict(Title = video['snippet']['title'],
                                   video_id = video['id'],
                                 audio_lang = video['snippet'].get('defaultAudioLanguage','NA'),
                                video_duration = video['contentDetails']['duration'],
                                  views = video['statistics']['viewCount'],
                                  likes = video['statistics']['likeCount'],
                                  comments = video['statistics']['commentCount'],
                                 )
                all_video_stats.append(video_stats)
            
    return all_video_stats

In [20]:
len(get_video_details(youtube,all_video_ids))

228

In [21]:
video_details = get_video_details(youtube,all_video_ids)

In [22]:
video_df = pd.DataFrame(video_details)

In [23]:
video_df.head(10)

,Title,video_id,audio_lang,video_duration,views,likes,comments
0,Splendor (8K Full Video) : Satbir Aujla | Shar...,RqKaqJCAg2M,pa,PT3M46S,254662,1395,14
1,Jimmy Choo Choo (8K Full Video) : Guri | B Pra...,v59drV-bHH4,pa,PT3M28S,15830,220,1
2,Rabb Wangu (8K Full Video) : Jass Manak | Late...,4khclgs-m8o,pa,PT2M11S,7224,74,3
3,Juti Jharrke (8K Full Video) : Hardeep Grewal ...,jOKAP9Hx0vY,pa,PT3M34S,18804,291,6
4,Saiyaan (8K Full Video) : Jass Manak | Sanjeed...,nfYa2ZQfVBY,pa,PT3M,478518,7231,52
5,Jass Manak (All Songs) | Jass Manak All Punjab...,TnW9BYo-sZ8,pa,PT3H22M17S,2405,70,4
6,Heeriye (8k Full Video) : Arjun Sahota | Gagan...,lNs10mghW3s,pa,PT3M22S,9699,185,1
7,Guitar (8K Full Video) : Karan Randhawa | Ayes...,Ltl-o0f73TY,pa,PT2M35S,22847,322,3
8,Istanbul (Full Song) Bhanu Pratap Agnihotri | ...,0OHUVp8SbH4,pa,PT3M,113093,4087,534
9,ROMANTIC AMLI : VADDA GREWAL (Official Video) ...,F1KK4-hWjrU,pa,PT3M20S,1363046,14727,1109

In [24]:
video_df.shape

(228, 7)

In [25]:
df_punjabi = pd.merge(punjabi_song_df,video_df,on="video_id",how='inner')

In [26]:
df_punjabi.shape

(228, 11)

In [40]:
df_punjabi.head(2)

,channel_title,song_name,release_date,description,video_id,Title,audio_lang,video_duration,views,likes,comments
0,Geet MP3 Punjabi,Splendor (8K Full Video) : Satbir Aujla | Shar...,2026-10-15T12:30:05Z,Geet MP3 presents the enhanced 8K full video o...,RqKaqJCAg2M,Splendor (8K Full Video) : Satbir Aujla | Shar...,pa,PT3M46S,254662,1395,14
1,Geet MP3 Punjabi,Jimmy Choo Choo (8K Full Video) : Guri | B Pra...,2026-10-13T12:30:03Z,Geet MP3 presents the enhanced 8K video of “Sa...,v59drV-bHH4,Jimmy Choo Choo (8K Full Video) : Guri | B Pra...,pa,PT3M28S,15830,220,1

# Geet MP3 Haryanvi

In [29]:
playlist_id_get_haryanvi = channel_data.loc[channel_data['channel_name']=='Geet MP3 Haryanvi','playlist_id'].iloc[0]
playlist_id_get_haryanvi

'UUpx43GnPYdqFXWnsuxLaljQ'

In [31]:
video_ids_haryanvi = get_video_ids(youtube,playlist_id_get_haryanvi)
len(video_ids_haryanvi)

80

In [32]:
haryanvi_df = pd.DataFrame(video_ids_haryanvi)
haryanvi_df.head(2)

,channel_title,song_name,release_date,description,video_id
0,Geet MP3 Haryanvi,Permissions (Full Video) : Archit Haritash | S...,2026-04-23T12:30:06Z,Geet MP3 Haryanvi presents the full video of “...,rG7tMHi-joQ
1,Geet MP3 Haryanvi,Baman Love (Full Video) : Mr Dutt | Jazz Dee |...,2026-04-03T04:30:05Z,"A beautiful and romantic Haryanvi song, “Baman...",SFYWVIPIEUQ

In [34]:
all_video_ids = haryanvi_df['video_id']
all_video_ids[0]

'rG7tMHi-joQ'

In [36]:
video_details = get_video_details(youtube,all_video_ids)
len(video_details)

80

In [37]:
all_video_df = pd.DataFrame(video_details)
all_video_df.head(2)

,Title,video_id,audio_lang,video_duration,views,likes,comments
0,Permissions (Full Video) : Archit Haritash | S...,rG7tMHi-joQ,en,PT2M50S,373712,3437,547
1,Baman Love (Full Video) : Mr Dutt | Jazz Dee |...,SFYWVIPIEUQ,en,PT2M3S,599313,15216,1132

In [39]:
df_haryanvi = pd.merge(haryanvi_df,all_video_df,on="video_id",how='inner')
df_haryanvi.shape

(80, 11)

# Geet mp3 Devotional

In [42]:
playlist_id_get_devotional = channel_data.loc[channel_data['channel_name']=='Geet MP3 Devotional','playlist_id'].iloc[0]
playlist_id_get_devotional

'UUW6cVdRxRuhk8nhg1pd3PNg'

In [43]:
video_ids_devotional = get_video_ids(youtube,playlist_id_get_devotional)
len(video_ids_devotional)

21

In [44]:
devotional_df = pd.DataFrame(video_ids_devotional)
devotional_df.head(2)

,channel_title,song_name,release_date,description,video_id
0,Geet MP3 Devotional,Puttar Gobind De (Full Video) : Onkar Malhi | ...,2025-12-22T09:29:26Z,"Presenting ""Puttar Gobind De"" sung by Onkar Ma...",KakRdTouAwQ
1,Geet MP3 Devotional,Anand Sahib (Full Path) : Sukhchain Singh Kakr...,2025-11-04T12:30:05Z,"Dive into the blissful verses of Anand Sahib, ...",GfW9aFH-1c0

In [47]:
all_video_ids_devotional = devotional_df['video_id']
all_video_ids_devotional[0]

'KakRdTouAwQ'

In [48]:
video_details_devotional = get_video_details(youtube,all_video_ids_devotional)
len(video_details_devotional)

21

In [49]:
all_video_devotional_df = pd.DataFrame(video_details_devotional)
all_video_devotional_df.head(2)

,Title,video_id,audio_lang,video_duration,views,likes,comments
0,Puttar Gobind De (Full Video) : Onkar Malhi | ...,KakRdTouAwQ,en-IN,PT3M40S,161165,5332,535
1,Anand Sahib (Full Path) : Sukhchain Singh Kakr...,GfW9aFH-1c0,en-IN,PT21M22S,23622,57,3

In [51]:
df_devotional = pd.merge(devotional_df,all_video_devotional_df,on="video_id",how='inner')
df_devotional.shape

(21, 11)

# getmp3 all

In [52]:
playlist_id_get_mp3 = channel_data.loc[channel_data['channel_name']=='Geet MP3','playlist_id'].iloc[0]
playlist_id_get_mp3

'UUlZF7OsrECe3t_ADrjZEh_Q'

In [54]:
video_ids_getmp3 = get_video_ids(youtube,playlist_id_get_mp3)
len(video_ids_getmp3)

850

In [55]:
getmp3_df = pd.DataFrame(video_ids_getmp3)
getmp3_df.head(2)

,channel_title,song_name,release_date,description,video_id
0,Geet MP3,DIOR: ARJUN SAHOTA (Full Song) Gagan Dhillon |...,2026-10-13T12:30:03Z,Geet MP3 proudly presents the official full au...,9AyMn4g3wVI
1,Geet MP3,DEEWANE: ARJUN SAHOTA (Full Video) Gagan Dhill...,2026-09-13T12:30:03Z,Geet MP3 presents a new soothing romantic song...,s89tjDD4YIs

In [56]:
all_video_ids_getmp3 = getmp3_df['video_id']
all_video_ids_getmp3[0]

'9AyMn4g3wVI'

In [57]:
video_details_getmp3 = get_video_details(youtube,all_video_ids_getmp3)
len(video_details_getmp3)

850

In [59]:
all_video_getmp3_df = pd.DataFrame(video_details_getmp3)
all_video_getmp3_df.head(2)

,Title,video_id,audio_lang,video_duration,views,likes,comments
0,DIOR: ARJUN SAHOTA (Full Song) Gagan Dhillon |...,9AyMn4g3wVI,en,PT3M25S,1084538,11615,2276
1,DEEWANE: ARJUN SAHOTA (Full Video) Gagan Dhill...,s89tjDD4YIs,en,PT3M16S,2077172,24098,2136

In [60]:
df_getmp3 = pd.merge(getmp3_df,all_video_getmp3_df,on="video_id",how='inner')
df_getmp3.shape

(850, 11)

# Export dataframes in excel file

In [61]:
# with pd.ExcelWriter('getmp3_songs.xlsx', engine='openpyxl') as writer:
#     df_getmp3.to_excel(writer, sheet_name='getmp3_songs', index=False)
#     df_punjabi.to_excel(writer, sheet_name='punjabi_songs', index=False)
#     df_haryanvi.to_excel(writer, sheet_name='haryanvi_songs', index=False)
#     df_devotional.to_excel(writer, sheet_name='devotional_songs', index=False)